name: Build and deploy container to Azure App Service

on:
  push:
    branches: [ "main" ]

env:
  ACR_LOGIN_SERVER: takehomeassigment.azurecr.io
  IMAGE_NAME: myapp
  WEBAPP_NAME: takehomeassigment
  RESOURCE_GROUP: takehomeassigment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name takehomeassigment

      - name: Build and push (linux/amd64)
        run: |
          docker buildx create --use --name builder || true
          docker buildx build \
            --platform linux/amd64 \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest \
            --push \
            .

      - name: Restart Web App (force pull latest)
        run: |
          az webapp restart -g $RESOURCE_GROUP -n $WEBAPP_NAME
